### ISSUE TITLE
razor-desktop hides already running stuff when launched

### ISSUE THREAD

**Issue by zabbal** [Razor-qt/razor-qt#664]
I'd like to use razor-desktop as a replacement of desktop app supplied by my DE but the problem is that if smth is launched before (like firefox for example) razor-desktop draws on top of that completely hiding everything. Would be much better if there would be an option to force it to draw 'under' the existing apps.

**Comment by jleclanche** [comment]
The Razor project is no longer maintained. It has merged with LXQt: http://lxqt.org/
