### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by graysky2** [Razor-qt/razor-qt#665]
Is development of this project hosted elsewhere or is it just dead?  Last updated was 15-May-2014 (https://github.com/Razor-qt/razor-qt/commit/ce5cc1d1b1a637e2d52d24ae60674cdc85f70ec3).

**Comment by kuzmas** [comment]
Razor-qt was merged with LXDE to become LXQt. Razor-qt itself is not under development any more. Please look at LXQt.
